### ISSUE TITLE
Errors with ImagCDF description in Technical Manual V5.0.0

### ISSUE THREAD

**Issue by SimonFlower** [INTERMAGNET/wg-tech-man#2]
I've just noticed a few errors in the ImagCDF description in the Technical Manual. Page numbers refer to the PDF version of the manual, available from the Intermagnet web site:

1. P.128 - the attribute name "Title1" should be "Title"
2. P.133 - in the table of variable attributes, the final number on the end of every attribute name should be in superscript font, to
   reference notes above the table. A list of affected attribute names:
   - FIELDNAM1 should be FIELDNAM<sup>1</sup>
   - UNITS1 should be UNITS<sup>1</sup>
   - FILLVAL1 should be FILLVAL<sup>1</sup>
   - VALIDMIN1 should be VALIDMIN<sup>1</sup> 
   - VALIDMAX1 should be VALIDMAX<sup>1</sup> 
   - DEPEND_02 should be DEPEND_0<sup>2</sup>
   - DISPLAY_TYPE2 should be DISPLAY_TYPE<sup>2</sup>
   - LABLAXIS2 should be LABLAXIS<sup>2</sup>

**Comment by bstlouis** [comment]
Thanks for noticing the conversion to readthedocs error.  I am meeting with Stephan bi-weekly, and we will take care of it.

**Comment by stephanbracke** [comment]
Did the asked changes and updated it in the development stream on the test site : 
https://test-manual.readthedocs.io/en/development/appendices/dataformats.html#imagcdfv1-2-intermagnet-exchange-format

**Comment by SimonFlower** [comment]
Thanks Stephan - that looks right now. The whole ReadTheDocs site is really nice.
